### ISSUE TITLE
Find cartoon character speech model

### ISSUE THREAD

**Issue by ShreytamGoyal** [StembleXYZ/cartoon-ai#4]

**Comment by BetterCallSaud** [comment]
Turns out there is no Mickey Mouse model in ElevenLabs VoiceLibrary.

So we're gonna need to purchase the Starter Pack on ElevenLabs ($1 for first month, then $5/month onwards). After that, we give it a 1 minute audio file of Mickey Mouse speaking clear words, and then it creates a voice model.

Then, finally, we use that in our TTS model.
